#!/usr/bin/env python3

"""
Get firewall rule target tag
"""

import sys
import subprocess
import json
import string

def main(project, fw_rule):
	target_tag = subprocess.check_output("gcloud compute firewall-rules describe %s --project %s --format=json | jq -r '.targetTags[]'" % (fw_rule, project), shell=True, encoding="utf8").rstrip()

	# generate dummy output to avoid Terraform External Data Source error:
	# 'Program output must be a JSON encoded map of string keys and string values'
	output = json.dumps({"target_tag": target_tag})
	
	print(output)

if __name__ == "__main__":
	# read input variables from stdin
	input = sys.stdin.read()
	input_json = json.loads(input)

	main(project=input_json.get('project'), fw_rule=input_json.get('fw_rule'))
